;PROGRAMA QUE COMPARA LOS VOLTAJES DE TRES POTENCIOMETROS CONECTADOS A LOS CANALES A0, A1, A2
;RESPECTIVAMENTE CON LAS SALIDAS EN EL PUERTO B QUE SE MUESTRAN:

;		_________________________________________________
;		SEÑAL						PB2		PB1		PB0
;		-------------------------	----	----	-----
;		VAR1 > VAR2 Y VAR3			  0		  0		  1
;		VAR2 > VAR1 Y VAR3			  0		  1		  1
;		VAR3 > VAR1 Y VAR2			  1		  1		  1
;		_________________________________________________


#INCLUDE <P16F877A.INC>
; Variables para el DELAY
valor1 equ h'21'
valor2 equ h'22'
valor3 equ h'23'

cte1 equ 10h 
cte2 equ 50h
cte3 equ 60h

PDEL0 EQU 0X24

VAR1 EQU 0X25				;VARIABLES PARA ALMACENAR LOS RESULTADOS DEL CAD
VAR2 EQU 0X26
VAR3 EQU 0X27

TEMP EQU 0X28

	ORG 0000H
	GOTO INICIO
	ORG 0005H

INICIO 
	CLRF PORTA 				;1.LIMPIA EL PUERTO A
	BSF STATUS,RP0			;2. CAMBIA AL BANCO 1
	CLRF ADCON1				;3. CONFIGURA EL PUERTO A COMO ENTRADAS ANALOGICAS 
	CLRF TRISB				; PUERTO B COMO SALIDAS

	BSF TXSTA,BRGH
	MOVLW .64
	MOVWF SPBRG
	BCF TXSTA,SYNC
	BSF TXSTA,TXEN

	BCF STATUS,RP0			; REGRESA AL BANCO 0
	
	BSF RCSTA,CREN
	BSF RCSTA,SPEN
	CLRF PORTB
	
	MOVLW B'1000001'
	MOVWF ADCON0					; 4. SELECCIONA LA FUENTE DE RELOJ,CANAL Y ENCIENDE EL CAD 

LOOP
	MOVLW '0'
	MOVWF TEMP
	BCF ADCON0,3
	BCF ADCON0,4					;SELECIONO EL CANAL 0
	CALL retardo					;ESPERO 20 MICROSEGUNDOS
	CALL retardo
	BSF ADCON0,2					;5. GO, COMIENZA LA CONVERSION DE AD

ESPERA
	BTFSC ADCON0,2				;6. ESPERA A QUE TERMINE LA CONVERSION
	GOTO ESPERA 
	MOVF ADRESH,W				;7. LEER EL RESULDADO DE LA CONVERSION 
	MOVWF VAR1					;GUARDA EL VALOR EN VAR1
	BSF ADCON0,3				; CAMBIA AL CANAL 1
	CALL retardo				; ESPERO 20 MICROSEGUNDOS
	CALL retardo
	BSF ADCON0,2				; GO, COMIENZA CON LA CONVERSION AD

ESPERA2
	BTFSC ADCON0,2				;ESPERA A QUE TERMINE LA CONVERSION 
	GOTO ESPERA2
	MOVF ADRESH,W
	MOVWF VAR2					;GUARDA EL VALOR EN VAR2
	BCF ADCON0,3
	BSF ADCON0,4				;CAMBIA AL CANAL 2
	CALL retardo
	CALL retardo
	BSF ADCON0,2				; GO

ESPERA3 
	BTFSC ADCON0,2				;ESPERA A QUE TERMINE LA CONVERSION 
	GOTO ESPERA3
	MOVF ADRESH,W
	MOVWF VAR3					;GUARDA EL VALOR EN VAR3
	MOVF VAR2,W
	SUBWF VAR1,W				; W = VAR1 - VAR2
	BTFSS STATUS,C				;¿VAR1 >= VAR2?, ¿ C= 1?
	GOTO _V2_V3_				; NO
	MOVF VAR3,W					; SI
	SUBWF VAR1,W				; W = VAR1 - VAR3
	BTFSS STATUS,C				; ¿ VAR1 >= VAR3?, ¿ C= 1?
	GOTO W_ES_7				; NO
	MOVLW 1						; SI
	GOTO ENVIA

_V2_V3_
	MOVF VAR3,W 
	SUBWF VAR2,W				; W = VAR2 - VAR3
	BTFSS STATUS,C				; ¿ VAR2 >= VAR3 ?, ¿ C = 1 ?
	GOTO W_ES_7					; NO
	MOVLW A'1'
	MOVWF TEMP
	MOVLW 3
	GOTO ENVIA

W_ES_7
	MOVLW A'2'
	MOVWF TEMP
	MOVLW 7

ENVIA
	MOVWF PORTB
	MOVF TEMP,W
	MOVWF TXREG
	BSF STATUS,RP0

ESPERA_ENVIO
	BTFSS TXSTA,TRMT
	GOTO ESPERA_ENVIO
	BCF STATUS,RP0
	CALL retardo
	GOTO LOOP
retardo movlw cte1   ;Rutina que genera un DELAY
     movwf valor1
tres movwf cte2
     movwf valor2
dos  movlw cte3
     movwf valor3
uno  decfsz valor3 
     goto uno 
     decfsz valor2
     goto dos
     decfsz valor1   
     goto tres
     return
     end

	END