 processor 16f877
  include<p16f877.inc>
valor1 equ h'21'
valor2 equ h'22'
valor3 equ h'23'


#DEFINE DATO 25H				;LA DIRECCION SERVIRA COMO VARIABLE PARA LEER EL DATO A RECIBIR
#DEFINE REG_CORRIMIENTO 26H		;VALOR DEL REGISTRO DE CORRIMIENTO PARA LA SECUENCIA
#DEFINE SENTIDO_ROTACION 27H 	;NOS INDICARA EL SENTIDO DE LA SECUENCIA (IZQUIERDA/DERECHA)

	ORG 0
	GOTO INICIO
	ORG 5

INICIO
	BSF STATUS,RP0			;1. CAMBIO AL BANCO 1 RAM
	CLRF TRISB				
	BSF TXSTA,BRGH			;2. SELECCIONA ALTA VELOCIDAD (TXSTA.BRG = 1)
	MOVLW .64
	MOVWF SPBRG				;3. VELOCIDAD DE 19200 BAUDS (0.16% ERROR)
	BCF TXSTA,SYNC			;4. MODO ASINCRONO SELECCIONADO (TXSTA.SYNC = 0)
	BSF TXSTA,TXEN			;5. HABILITA LA TRANSMICION (TXSTA.TXEN = 1)
	BCF STATUS,RP0			;6. REGRESO AL BANCO 0 DE RAM
	BSF RCSTA,CREN			;7. HABILITA LA RECEPCION DE DATOS (RCSTA,CREN = 1)
	BSF RCSTA,SPEN			;8. HABILITA EL PUERTO SERIE (RCSTA.SPEN = 1)
	CLRF PORTB
	MOVLW 0X80
	MOVWF REG_CORRIMIENTO
	MOVLW 1
	MOVWF SENTIDO_ROTACION

LOOP
	BTFSS PIR1,RCIF			;9. ESPERAR A QUE EL BUFER DE RECEPCION DEL USART ESTE LLENO
	GOTO CONTINUA

CAMBIA_DATO
	MOVF RCREG,W			; LEO EL DATO RECIBIDO
	MOVWF DATO

CONTINUA
	MOVLW '0'
	SUBWF DATO,W				;W = DATO - '0'
	BTFSC STATUS,Z
	GOTO APAGADOS
	MOVLW '1'
	SUBWF DATO,W				;W = DATO - '1'
	BTFSC STATUS,Z
	GOTO ENCENDIDOS
	MOVLW '2'
	SUBWF DATO,W				;W = DATO - '2'
	BTFSC STATUS,Z
	GOTO DERECHA
	MOVLW '3'
	SUBWF DATO,W				;W = DATO - '3'
	BTFSC STATUS,Z
	GOTO IZQUIERDA
	MOVLW '4'
	SUBWF DATO,W				;W = DATO - '4'
	BTFSC STATUS,Z
	GOTO REBOTA
	MOVLW '5'
	SUBWF DATO,W				;W = DATO - '5'
	BTFSC STATUS,Z
	GOTO BLINK

APAGADOS
	CLRF PORTB
	GOTO LOOP

ENCENDIDOS
	MOVLW .255
	MOVWF PORTB
	GOTO LOOP
DERECHA
	BCF STATUS,C				; SECUENCIA HACIA LA DERECHA 
	MOVF REG_CORRIMIENTO,W
	MOVWF PORTB
	CALL RETARDO
	RRF REG_CORRIMIENTO,F
	BTFSS STATUS,C
	GOTO LOOP
	MOVLW 0X80
	MOVWF REG_CORRIMIENTO
	GOTO LOOP

IZQUIERDA 						;SECUENCIA HACIA LA IZQUIERDA 
	BCF STATUS,C				
	MOVF REG_CORRIMIENTO,W
	MOVWF PORTB
	CALL RETARDO
	RLF REG_CORRIMIENTO,F
	BTFSS STATUS,C
	GOTO LOOP
	MOVLW 0X01
	MOVWF REG_CORRIMIENTO
	GOTO LOOP

REBOTA
	BCF STATUS,C				
	MOVF REG_CORRIMIENTO,W
	MOVWF PORTB
	CALL RETARDO
	MOVF SENTIDO_ROTACION,W
	BTFSS STATUS,Z
	GOTO SENT_DER				;SENTIDO_ROTACION = 1: DERECHA

SENT_IZQ						;SENTIDO_ROTACION = 0: IZQUIERDA
	RLF REG_CORRIMIENTO,F
	BTFSS STATUS,C
	GOTO LOOP					;C=0
	MOVLW 0X80					;C=1
	MOVWF REG_CORRIMIENTO
	MOVLW 1
	MOVWF SENTIDO_ROTACION
	GOTO LOOP

SENT_DER
	RRF REG_CORRIMIENTO,F
	BTFSS STATUS,C
	GOTO LOOP					;C=0
	MOVLW 0X01					;C=1
	MOVWF REG_CORRIMIENTO
	MOVLW 0
	MOVWF SENTIDO_ROTACION
	GOTO LOOP
 

BLINK
	MOVLW .255
	MOVWF PORTB
	CALL RETARDO
	CLRF PORTB
	CALL RETARDO

       ;Rutina que genra un Retardo
RETARDO: 
     movlw 15h       
	 movwf valor1
tres movlw 60h
	 movwf valor2
dos  movlw 50h
	 movwf valor3
uno  decfsz valor3 
	 goto uno 
	 decfsz valor2
	 goto dos
	 decfsz valor1   
	 goto tres
	 return 

	END